### PR TITLE
Restored the Networking module to request IP data in the default format

### PR DESCRIPTION
**Pull request by hachotze**
## Description
Restored the Networking module to request and process IP data in the default format. The prior implementation that used the ip(8) '-json' flag was found to have a support gap on Debian 9, where the flag is unavailable.

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-osconfig/blob/main/CONTRIBUTING.md).
- [x] I added unit-tests to validate my changes. All unit tests are passing.
- [x] I have merged the latest `main` branch prior to this PR submission.
- [x] I submitted this PR against the `main` branch.

### CODE REVIEW

**Review by robertschaedler3 — COMMENTED** [review]
@hachotze, do these changes to network data format have any effect on the data that is reported to the IoTHub?

**Comment by MariusNi** [comment]
Thanks for this PR! Second what was asked here, is this change projected to change the reported payloads for Networking? Was the change tested end to end to ensure no regression on Ubuntu with the Debian fix?  

---
In reply to: [810216369](https://github.com/Azure/azure-osconfig/pull/24#issuecomment-810216369) [](http://example.com/codeflow?ancestors=810216369,810216369)

**Comment by hachotze** [comment]
> Thanks for this PR! Second what was asked here, is this change projected to change the reported payloads for Networking? Was the change tested end to end to ensure no regression on Ubuntu with the Debian fix?
> 
> In reply to: [810216369](https://github.com/Azure/azure-osconfig/pull/24#issuecomment-810216369)

Reported payloads will not be affected and the change has been validated on Ubuntu and Debian. Thank you for the CR!

**Comment by hachotze** [comment]
> @hachotze, do these changes to network data format have any effect on the data that is reported to the IoTHub?

Reported payloads will not be affected. Thank you for the CR!

**Review by MariusNi — APPROVED** [review]
:shipit:

**Comment by MariusNi** [comment]
Please answer to the PR checklist.  

---
In reply to: [974309108](https://github.com/Azure/azure-osconfig/pull/24#issuecomment-974309108) [](http://example.com/codeflow?ancestors=974309108,974309108)

**Review by robertschaedler3 — APPROVED** [review]

**Review by MariusNi — APPROVED** [review]
:shipit:

**Pull request merged**
