### PR TITLE
Move fuzzer under tests directory

### PR DESCRIPTION
**Pull request by robertwoj-microsoft**
## Description

Move the fuzzer implementation under tests directory as requested in comments under [the CI workflow PR](https://github.com/Azure/azure-osconfig/pull/792).

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-osconfig/blob/main/CONTRIBUTING.md).
- [x] All unit tests are passing.
- [x] I have merged the latest `main` branch prior to this PR submission.
- [x] I submitted this PR against the `main` branch.

### CODE REVIEW

**Review by MariusNi — APPROVED** [review]
:shipit:

**Review by AhmedBM — APPROVED** [review]
👌

**Review by MariusNi — CHANGES_REQUESTED** [review]
:clock1:

**Review by MariusNi — DISMISSED** [review]
:shipit:

**Review by MariusNi — APPROVED** [review]
:shipit:

**Pull request merged**
